In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer

In [2]:
df = pd.read_csv("brfss_reduced.csv")
df

,CHD_OR_MI,SEX,AGE,HEALTH,PHYSICAL_HEALTH,MENTAL_HEALTH,PHYSICAL_ACTIVITIES,BLOOD_PRESSURE,HIGH_CHOLESTEROL,SKIN_CANCER,...,DIFFICULTY_WALKING,SMOKE,TABACCO_PRODUCTS,E_CIGARETTES,HEAVY_DRINKERS,HIV,FRUITS,VEGETABLES,FRIED_POTATOES,ETHNICITY
0,2.0,2,70,2.0,3.0,2.0,2.0,1.0,1.0,2.0,...,2.0,1.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1
1,1.0,2,67,1.0,1.0,1.0,1.0,2.0,1.0,2.0,...,1.0,2.0,3.0,3.0,1.0,2.0,1.0,1.0,3.0,2
2,1.0,2,72,1.0,1.0,1.0,2.0,2.0,2.0,2.0,...,2.0,2.0,3.0,3.0,1.0,2.0,1.0,2.0,1.0,2
3,2.0,2,62,1.0,1.0,2.0,1.0,2.0,1.0,2.0,...,2.0,2.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1
4,1.0,1,76,2.0,3.0,1.0,1.0,1.0,1.0,2.0,...,1.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,2.0,2,30,1.0,1.0,3.0,1.0,2.0,2.0,2.0,...,2.0,1.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,2
438689,2.0,1,80,1.0,1.0,1.0,2.0,2.0,2.0,2.0,...,2.0,2.0,3.0,4.0,1.0,2.0,1.0,1.0,1.0,6
438690,2.0,1,54,1.0,1.0,1.0,1.0,1.0,1.0,2.0,...,2.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,3.0,2
438691,2.0,1,67,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,2.0,2.0,3.0,4.0,1.0,1.0,1.0,1.0,3.0,2
438692,2.0,2,45,1.0,2.0,2.0,1.0,1.0,1.0,2.0,...,2.0,2.0,3.0,3.0,1.0,1.0,2.0,2.0,2.0,2

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438693 entries, 0 to 438692
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   CHD_OR_MI            434058 non-null  float64
 1   SEX                  438693 non-null  int64
 2   AGE                  438693 non-null  int64
 3   HEALTH               437532 non-null  float64
 4   PHYSICAL_HEALTH      429199 non-null  float64
 5   MENTAL_HEALTH        430776 non-null  float64
 6   PHYSICAL_ACTIVITIES  437765 non-null  float64
 7   BLOOD_PRESSURE       436781 non-null  float64
 8   HIGH_CHOLESTEROL     374713 non-null  float64
 9   SKIN_CANCER          437252 non-null  float64
 10  CANCER               437329 non-null  float64
 11  BRONCHITIS           436586 non-null  float64
 12  DEPRESSIVE_DISORDER  436176 non-null  float64
 13  KIDNEY_DISEASE       436880 non-null  float64
 14  DIABETES             437708 non-null  float64
 15  ARTHRITIS            435797 non-null  float64
 16  BMI                  391841 non-null  float64
 17  DIFFICULTY_WALKING   418863 non-null  float64
 18  SMOKE                414232 non-null  float64
 19  TABACCO_PRODUCTS     415811 non-null  float64
 20  E_CIGARETTES         414755 non-null  float64
 21  HEAVY_DRINKERS       403700 non-null  float64
 22  HIV                  386837 non-null  float64
 23  FRUITS               387606 non-null  float64
 24  VEGETABLES           378566 non-null  float64
 25  FRIED_POTATOES       393928 non-null  float64
 26  ETHNICITY            438693 non-null  int64
dtypes: float64(24), int64(3)
memory usage: 90.4 MB

In [4]:
df['CHD_OR_MI'] = df['CHD_OR_MI'].astype('Int64')
df['HEALTH'] = df['HEALTH'].astype('Int64')
df['PHYSICAL_HEALTH'] = df['PHYSICAL_HEALTH'].astype('Int64')
df['MENTAL_HEALTH'] = df['MENTAL_HEALTH'].astype('Int64')
df['PHYSICAL_ACTIVITIES'] = df['PHYSICAL_ACTIVITIES'].astype('Int64')
df['BLOOD_PRESSURE'] = df['BLOOD_PRESSURE'].astype('Int64')
df['HIGH_CHOLESTEROL'] = df['HIGH_CHOLESTEROL'].astype('Int64')
df['SKIN_CANCER'] = df['SKIN_CANCER'].astype('Int64')
df['CANCER'] = df['CANCER'].astype('Int64')
df['BRONCHITIS'] = df['BRONCHITIS'].astype('Int64')
df['DEPRESSIVE_DISORDER'] = df['DEPRESSIVE_DISORDER'].astype('Int64')
df['KIDNEY_DISEASE'] = df['KIDNEY_DISEASE'].astype('Int64')
df['DIABETES'] = df['DIABETES'].astype('Int64')
df['BMI'] = df['BMI'].astype('Int64')
df['ARTHRITIS'] = df['ARTHRITIS'].astype('Int64')
df['DIFFICULTY_WALKING'] = df['DIFFICULTY_WALKING'].astype('Int64')
df['SMOKE'] = df['SMOKE'].astype('Int64')
df['TABACCO_PRODUCTS'] = df['TABACCO_PRODUCTS'].astype('Int64')
df['E_CIGARETTES'] = df['E_CIGARETTES'].astype('Int64')
df['HEAVY_DRINKERS'] = df['HEAVY_DRINKERS'].astype('Int64')
df['HIV'] = df['HIV'].astype('Int64')
df['FRUITS'] = df['FRUITS'].astype('Int64')
df['VEGETABLES'] = df['VEGETABLES'].astype('Int64')
df['FRIED_POTATOES'] = df['FRIED_POTATOES'].astype('Int64')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438693 entries, 0 to 438692
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   CHD_OR_MI            434058 non-null  Int64
 1   SEX                  438693 non-null  int64
 2   AGE                  438693 non-null  int64
 3   HEALTH               437532 non-null  Int64
 4   PHYSICAL_HEALTH      429199 non-null  Int64
 5   MENTAL_HEALTH        430776 non-null  Int64
 6   PHYSICAL_ACTIVITIES  437765 non-null  Int64
 7   BLOOD_PRESSURE       436781 non-null  Int64
 8   HIGH_CHOLESTEROL     374713 non-null  Int64
 9   SKIN_CANCER          437252 non-null  Int64
 10  CANCER               437329 non-null  Int64
 11  BRONCHITIS           436586 non-null  Int64
 12  DEPRESSIVE_DISORDER  436176 non-null  Int64
 13  KIDNEY_DISEASE       436880 non-null  Int64
 14  DIABETES             437708 non-null  Int64
 15  ARTHRITIS            435797 non-null  Int64
 16  BMI                  391841 non-null  Int64
 17  DIFFICULTY_WALKING   418863 non-null  Int64
 18  SMOKE                414232 non-null  Int64
 19  TABACCO_PRODUCTS     415811 non-null  Int64
 20  E_CIGARETTES         414755 non-null  Int64
 21  HEAVY_DRINKERS       403700 non-null  Int64
 22  HIV                  386837 non-null  Int64
 23  FRUITS               387606 non-null  Int64
 24  VEGETABLES           378566 non-null  Int64
 25  FRIED_POTATOES       393928 non-null  Int64
 26  ETHNICITY            438693 non-null  int64
dtypes: Int64(24), int64(3)
memory usage: 100.4 MB

In [6]:
df.isna().sum()

CHD_OR_MI               4635
SEX                        0
AGE                        0
HEALTH                  1161
PHYSICAL_HEALTH         9494
MENTAL_HEALTH           7917
PHYSICAL_ACTIVITIES      928
BLOOD_PRESSURE          1912
HIGH_CHOLESTEROL       63980
SKIN_CANCER             1441
CANCER                  1364
BRONCHITIS              2107
DEPRESSIVE_DISORDER     2517
KIDNEY_DISEASE          1813
DIABETES                 985
ARTHRITIS               2896
BMI                    46852
DIFFICULTY_WALKING     19830
SMOKE                  24461
TABACCO_PRODUCTS       22882
E_CIGARETTES           23938
HEAVY_DRINKERS         34993
HIV                    51856
FRUITS                 51087
VEGETABLES             60127
FRIED_POTATOES         44765
ETHNICITY                  0
dtype: int64

In [7]:
df = df.dropna(subset=['MENTAL_HEALTH'])
df = df.dropna(subset=['CHD_OR_MI'])
df = df.dropna(subset=['ARTHRITIS'])
df = df.dropna(subset=['DEPRESSIVE_DISORDER'])
df = df.dropna(subset=['BRONCHITIS'])
df = df.dropna(subset=['BLOOD_PRESSURE'])
df = df.dropna(subset=['KIDNEY_DISEASE'])
df = df.dropna(subset=['SKIN_CANCER'])
df = df.dropna(subset=['CANCER'])
df = df.dropna(subset=['HEALTH'])
df = df.dropna(subset=['DIABETES'])
df = df.dropna(subset=['PHYSICAL_ACTIVITIES'])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 415160 entries, 0 to 438692
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   CHD_OR_MI            415160 non-null  Int64
 1   SEX                  415160 non-null  int64
 2   AGE                  415160 non-null  int64
 3   HEALTH               415160 non-null  Int64
 4   PHYSICAL_HEALTH      408684 non-null  Int64
 5   MENTAL_HEALTH        415160 non-null  Int64
 6   PHYSICAL_ACTIVITIES  415160 non-null  Int64
 7   BLOOD_PRESSURE       415160 non-null  Int64
 8   HIGH_CHOLESTEROL     356893 non-null  Int64
 9   SKIN_CANCER          415160 non-null  Int64
 10  CANCER               415160 non-null  Int64
 11  BRONCHITIS           415160 non-null  Int64
 12  DEPRESSIVE_DISORDER  415160 non-null  Int64
 13  KIDNEY_DISEASE       415160 non-null  Int64
 14  DIABETES             415160 non-null  Int64
 15  ARTHRITIS            415160 non-null  Int64
 16  BMI                  372360 non-null  Int64
 17  DIFFICULTY_WALKING   397057 non-null  Int64
 18  SMOKE                392719 non-null  Int64
 19  TABACCO_PRODUCTS     394012 non-null  Int64
 20  E_CIGARETTES         393003 non-null  Int64
 21  HEAVY_DRINKERS       383208 non-null  Int64
 22  HIV                  367508 non-null  Int64
 23  FRUITS               368781 non-null  Int64
 24  VEGETABLES           360984 non-null  Int64
 25  FRIED_POTATOES       374056 non-null  Int64
 26  ETHNICITY            415160 non-null  int64
dtypes: Int64(24), int64(3)
memory usage: 98.2 MB

In [9]:
df.isna().sum()

CHD_OR_MI                  0
SEX                        0
AGE                        0
HEALTH                     0
PHYSICAL_HEALTH         6476
MENTAL_HEALTH              0
PHYSICAL_ACTIVITIES        0
BLOOD_PRESSURE             0
HIGH_CHOLESTEROL       58267
SKIN_CANCER                0
CANCER                     0
BRONCHITIS                 0
DEPRESSIVE_DISORDER        0
KIDNEY_DISEASE             0
DIABETES                   0
ARTHRITIS                  0
BMI                    42800
DIFFICULTY_WALKING     18103
SMOKE                  22441
TABACCO_PRODUCTS       21148
E_CIGARETTES           22157
HEAVY_DRINKERS         31952
HIV                    47652
FRUITS                 46379
VEGETABLES             54176
FRIED_POTATOES         41104
ETHNICITY                  0
dtype: int64

In [10]:
df_missing_val = df.copy()

In [11]:
na_variables_cat = ['PHYSICAL_HEALTH','HIGH_CHOLESTEROL', 'DIFFICULTY_WALKING', 'SMOKE', 'TABACCO_PRODUCTS',
                'E_CIGARETTES', 'HEAVY_DRINKERS', 'HIV', 'FRUITS', 'VEGETABLES','FRIED_POTATOES']

In [12]:
na_variables_num = ['BMI']

In [14]:
def show_distr(df):
  print("missing values : \n{}".format(df.isna().sum()))
  boxplot = df.boxplot(column=na_variables)  
  hist = df[na_variables].hist(bins=20)
  print("\n -------------------------")

In [15]:
df.mode()

,CHD_OR_MI,SEX,AGE,HEALTH,PHYSICAL_HEALTH,MENTAL_HEALTH,PHYSICAL_ACTIVITIES,BLOOD_PRESSURE,HIGH_CHOLESTEROL,SKIN_CANCER,...,DIFFICULTY_WALKING,SMOKE,TABACCO_PRODUCTS,E_CIGARETTES,HEAVY_DRINKERS,HIV,FRUITS,VEGETABLES,FRIED_POTATOES,ETHNICITY
0,2,2,80,1,1,1,1,1,2,2,...,2,2,3,3,1,2,1,1,1,1

In [16]:
#numericos
from sklearn.impute import SimpleImputer
num_imp = SimpleImputer(strategy='median')
df[na_variables_num] = num_imp.fit_transform(df[na_variables_num])

In [17]:
df.isna().sum()

CHD_OR_MI                  0
SEX                        0
AGE                        0
HEALTH                     0
PHYSICAL_HEALTH         6476
MENTAL_HEALTH              0
PHYSICAL_ACTIVITIES        0
BLOOD_PRESSURE             0
HIGH_CHOLESTEROL       58267
SKIN_CANCER                0
CANCER                     0
BRONCHITIS                 0
DEPRESSIVE_DISORDER        0
KIDNEY_DISEASE             0
DIABETES                   0
ARTHRITIS                  0
BMI                        0
DIFFICULTY_WALKING     18103
SMOKE                  22441
TABACCO_PRODUCTS       21148
E_CIGARETTES           22157
HEAVY_DRINKERS         31952
HIV                    47652
FRUITS                 46379
VEGETABLES             54176
FRIED_POTATOES         41104
ETHNICITY                  0
dtype: int64

In [18]:
#categoricos
for col in na_variables_cat:
    mode_value = df[col].mode().iloc[0]
    df[col].fillna(value=mode_value, inplace=True)

In [19]:
df.isna().sum()

CHD_OR_MI              0
SEX                    0
AGE                    0
HEALTH                 0
PHYSICAL_HEALTH        0
MENTAL_HEALTH          0
PHYSICAL_ACTIVITIES    0
BLOOD_PRESSURE         0
HIGH_CHOLESTEROL       0
SKIN_CANCER            0
CANCER                 0
BRONCHITIS             0
DEPRESSIVE_DISORDER    0
KIDNEY_DISEASE         0
DIABETES               0
ARTHRITIS              0
BMI                    0
DIFFICULTY_WALKING     0
SMOKE                  0
TABACCO_PRODUCTS       0
E_CIGARETTES           0
HEAVY_DRINKERS         0
HIV                    0
FRUITS                 0
VEGETABLES             0
FRIED_POTATOES         0
ETHNICITY              0
dtype: int64

### Outliers

In [20]:
df['BMI'].describe()

count    415160.000000
mean       2842.692328
std         618.471801
min        1200.000000
25%        2441.000000
50%        2744.000000
75%        3109.000000
max        9933.000000
Name: BMI, dtype: float64

In [22]:
Q3 = np.percentile(df["BMI"], 80, interpolation = 'midpoint')
Q1 = np.percentile(df["BMI"], 20, interpolation = 'midpoint')
RIC = Q3 - Q1
df = df[(df['BMI'] <= Q3 + 1.5 * RIC) & (df['BMI'] >= Q1 - 1.5 * RIC)]

In [23]:
df['BMI'].describe()

count    406983.000000
mean       2797.221174
std         525.309873
min        1200.000000
25%        2439.000000
50%        2744.000000
75%        3074.000000
max        4512.000000
Name: BMI, dtype: float64

In [24]:
df.to_csv('brfss_pp1.csv', index=False)

In [66]:
#CÃ³digo para futuras entregas
from pyod.models.knn import KNN
clf = KNN(contamination=0.1, n_jobs=-1)
clf.fit(df)
y_pred = clf.predict(df)
df[y_pred == 0].shape
usar dask-ml

KeyboardInterrupt: