In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("brfss.csv")
df

,X_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,X_PSU,CTELENM1,...,X_FRTRES1,X_VEGRES1,X_FRUTSU1,X_VEGESU1,X_FRTLT1A,X_VEGLT1A,X_FRT16A,X_VEG23A,X_FRUITE1,X_VEGETE1
0,1,1,1192021,1,19,2021,1100,2021000001,2021000001,1.0,...,1,1,100.0,214.0,1,1,1,1,0,0
1,1,1,1212021,1,21,2021,1100,2021000002,2021000002,1.0,...,1,1,100.0,128.0,1,1,1,1,0,0
2,1,1,1212021,1,21,2021,1100,2021000003,2021000003,1.0,...,1,1,100.0,71.0,1,2,1,1,0,0
3,1,1,1172021,1,17,2021,1100,2021000004,2021000004,1.0,...,1,1,114.0,165.0,1,1,1,1,0,0
4,1,1,1152021,1,15,2021,1100,2021000005,2021000005,1.0,...,1,1,100.0,258.0,1,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,78,12,1062022,1,6,2022,1100,2021001381,2021001381,NaN,...,1,1,157.0,393.0,1,1,1,1,0,0
438689,78,12,1122022,1,12,2022,1100,2021001382,2021001382,NaN,...,1,1,200.0,157.0,1,1,1,1,0,0
438690,78,12,12212021,12,21,2021,1100,2021001383,2021001383,NaN,...,1,1,200.0,143.0,1,1,1,1,0,0
438691,78,12,1112022,1,11,2022,1100,2021001384,2021001384,NaN,...,1,1,100.0,156.0,1,1,1,1,0,0
438692,78,12,12222021,12,22,2021,1100,2021001385,2021001385,NaN,...,1,1,34.0,66.0,2,2,1,1,0,0

In [3]:
df['X_AGE80'].describe()

count    438693.000000
mean         54.702781
std          17.574022
min          18.000000
25%          41.000000
50%          57.000000
75%          69.000000
max          80.000000
Name: X_AGE80, dtype: float64

In [4]:
df.shape

(438693, 303)

In [5]:
brfss_reduced = df[['X_MICHD', 'X_SEX', 'X_AGE80', 'X_RFHLTH', 'X_PHYS14D', 'X_MENT14D', 'X_TOTINDA', 'X_RFHYPE6', 
                    'TOLDHI3','CHCSCNCR', 'CHCOCNCR', 'CHCCOPD3', 'ADDEPEV3', 'CHCKDNY2', 'DIABETE4', 
                    'X_DRDXAR3', 'X_BMI5', 'DIFFWALK', 'SMOKE100', 'USENOW3', 'ECIGNOW1', 'X_RFDRHV7', 
                    'HIVTST7', 'X_FRTLT1A', 'X_VEGLT1A', 'FRENCHF1', 'X_IMPRACE']]

In [6]:
brfss_reduced

,X_MICHD,X_SEX,X_AGE80,X_RFHLTH,X_PHYS14D,X_MENT14D,X_TOTINDA,X_RFHYPE6,TOLDHI3,CHCSCNCR,...,DIFFWALK,SMOKE100,USENOW3,ECIGNOW1,X_RFDRHV7,HIVTST7,X_FRTLT1A,X_VEGLT1A,FRENCHF1,X_IMPRACE
0,2.0,2,70,2,3,2,2,1,1.0,2.0,...,2.0,1.0,3.0,3.0,1,2.0,1,1,203.0,1
1,1.0,2,67,1,1,1,1,2,1.0,2.0,...,1.0,2.0,3.0,3.0,1,2.0,1,1,555.0,2
2,1.0,2,72,1,1,1,2,2,2.0,2.0,...,2.0,2.0,3.0,3.0,1,2.0,1,2,201.0,2
3,2.0,2,62,1,1,2,1,2,1.0,2.0,...,2.0,2.0,3.0,3.0,1,2.0,1,1,204.0,1
4,1.0,1,76,2,3,1,1,1,1.0,2.0,...,1.0,2.0,2.0,3.0,1,1.0,1,1,202.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,2.0,2,30,1,1,3,1,2,2.0,2.0,...,2.0,1.0,3.0,3.0,1,1.0,1,1,201.0,2
438689,2.0,1,80,1,1,1,2,2,2.0,2.0,...,2.0,2.0,3.0,4.0,1,2.0,1,1,201.0,6
438690,2.0,1,54,1,1,1,1,1,1.0,2.0,...,2.0,2.0,3.0,3.0,1,1.0,1,1,555.0,2
438691,2.0,1,67,1,1,1,1,2,2.0,2.0,...,2.0,2.0,3.0,4.0,1,1.0,1,1,555.0,2
438692,2.0,2,45,1,2,2,1,1,1.0,2.0,...,2.0,2.0,3.0,3.0,1,1.0,2,2,301.0,2

In [7]:
brfss_reduced.columns.values

array(['X_MICHD', 'X_SEX', 'X_AGE80', 'X_RFHLTH', 'X_PHYS14D',
       'X_MENT14D', 'X_TOTINDA', 'X_RFHYPE6', 'TOLDHI3', 'CHCSCNCR',
       'CHCOCNCR', 'CHCCOPD3', 'ADDEPEV3', 'CHCKDNY2', 'DIABETE4',
       'X_DRDXAR3', 'X_BMI5', 'DIFFWALK', 'SMOKE100', 'USENOW3',
       'ECIGNOW1', 'X_RFDRHV7', 'HIVTST7', 'X_FRTLT1A', 'X_VEGLT1A',
       'FRENCHF1', 'X_IMPRACE'], dtype=object)

In [8]:
brfss_reduced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438693 entries, 0 to 438692
Data columns (total 27 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   X_MICHD    434058 non-null  float64
 1   X_SEX      438693 non-null  int64
 2   X_AGE80    438693 non-null  int64
 3   X_RFHLTH   438693 non-null  int64
 4   X_PHYS14D  438693 non-null  int64
 5   X_MENT14D  438693 non-null  int64
 6   X_TOTINDA  438693 non-null  int64
 7   X_RFHYPE6  438693 non-null  int64
 8   TOLDHI3    377857 non-null  float64
 9   CHCSCNCR   438691 non-null  float64
 10  CHCOCNCR   438690 non-null  float64
 11  CHCCOPD3   438690 non-null  float64
 12  ADDEPEV3   438690 non-null  float64
 13  CHCKDNY2   438690 non-null  float64
 14  DIABETE4   438690 non-null  float64
 15  X_DRDXAR3  435797 non-null  float64
 16  X_BMI5     391841 non-null  float64
 17  DIFFWALK   420684 non-null  float64
 18  SMOKE100   417461 non-null  float64
 19  USENOW3    416704 non-null  float64
 20  ECIGNOW1   415668 non-null  float64
 21  X_RFDRHV7  438693 non-null  int64
 22  HIVTST7    408542 non-null  float64
 23  X_FRTLT1A  438693 non-null  int64
 24  X_VEGLT1A  438693 non-null  int64
 25  FRENCHF1   400582 non-null  float64
 26  X_IMPRACE  438693 non-null  int64
dtypes: float64(16), int64(11)
memory usage: 90.4 MB

In [10]:
columns = ['CHD_OR_MI', 'SEX', 'AGE', 'HEALTH', 'PHYSICAL_HEALTH',
       'MENTAL_HEALTH', 'PHYSICAL_ACTIVITIES', 'BLOOD_PRESSURE', 'HIGH_CHOLESTEROL',
       'SKIN_CANCER', 'CANCER', 'BRONCHITIS', 'DEPRESSIVE_DISORDER', 'KIDNEY_DISEASE',
       'DIABETES', 'ARTHRITIS', 'BMI', 'DIFFICULTY_WALKING', 'SMOKE',
       'TABACCO_PRODUCTS', 'E_CIGARETTES', 'HEAVY_DRINKERS', 'HIV', 'FRUITS',
       'VEGETABLES', 'FRIED_POTATOES', 'ETHNICITY']

In [11]:
brfss_reduced.columns = columns

In [12]:
brfss_reduced

,CHD_OR_MI,SEX,AGE,HEALTH,PHYSICAL_HEALTH,MENTAL_HEALTH,PHYSICAL_ACTIVITIES,BLOOD_PRESSURE,HIGH_CHOLESTEROL,SKIN_CANCER,...,DIFFICULTY_WALKING,SMOKE,TABACCO_PRODUCTS,E_CIGARETTES,HEAVY_DRINKERS,HIV,FRUITS,VEGETABLES,FRIED_POTATOES,ETHNICITY
0,2.0,2,70,2,3,2,2,1,1.0,2.0,...,2.0,1.0,3.0,3.0,1,2.0,1,1,203.0,1
1,1.0,2,67,1,1,1,1,2,1.0,2.0,...,1.0,2.0,3.0,3.0,1,2.0,1,1,555.0,2
2,1.0,2,72,1,1,1,2,2,2.0,2.0,...,2.0,2.0,3.0,3.0,1,2.0,1,2,201.0,2
3,2.0,2,62,1,1,2,1,2,1.0,2.0,...,2.0,2.0,3.0,3.0,1,2.0,1,1,204.0,1
4,1.0,1,76,2,3,1,1,1,1.0,2.0,...,1.0,2.0,2.0,3.0,1,1.0,1,1,202.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,2.0,2,30,1,1,3,1,2,2.0,2.0,...,2.0,1.0,3.0,3.0,1,1.0,1,1,201.0,2
438689,2.0,1,80,1,1,1,2,2,2.0,2.0,...,2.0,2.0,3.0,4.0,1,2.0,1,1,201.0,6
438690,2.0,1,54,1,1,1,1,1,1.0,2.0,...,2.0,2.0,3.0,3.0,1,1.0,1,1,555.0,2
438691,2.0,1,67,1,1,1,1,2,2.0,2.0,...,2.0,2.0,3.0,4.0,1,1.0,1,1,555.0,2
438692,2.0,2,45,1,2,2,1,1,1.0,2.0,...,2.0,2.0,3.0,3.0,1,1.0,2,2,301.0,2

In [13]:
brfss_reduced['FRIED_POTATOES'] = np.where((brfss_reduced['FRIED_POTATOES'] >= 100) & (brfss_reduced['FRIED_POTATOES'] <= 300), 1, brfss_reduced['FRIED_POTATOES'])
brfss_reduced['FRIED_POTATOES'] = np.where((brfss_reduced['FRIED_POTATOES'] >= 300) & (brfss_reduced['FRIED_POTATOES'] <= 400), 2, brfss_reduced['FRIED_POTATOES'])
brfss_reduced['FRIED_POTATOES'] = np.where((brfss_reduced['FRIED_POTATOES'] == 555), 3, brfss_reduced['FRIED_POTATOES'])

C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\2068654677.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['FRIED_POTATOES'] = np.where((brfss_reduced['FRIED_POTATOES'] >= 100) & (brfss_reduced['FRIED_POTATOES'] <= 300), 1, brfss_reduced['FRIED_POTATOES'])
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\2068654677.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['FRIED_POTATOES'] = np.where((brfss_reduced['FRIED_POTATOES'] >= 300) & (brfss_reduced['FRIED_POTATOES'] <= 400), 2, brfss_reduced['FRIED_POTATOES'])
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\2068654677.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['FRIED_POTATOES'] = np.where((brfss_reduced['FRIED_POTATOES'] == 555), 3, brfss_reduced['FRIED_POTATOES'])

In [14]:
brfss_reduced['FRIED_POTATOES'] = brfss_reduced['FRIED_POTATOES'].replace({777: '', 999: ''})

C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\1274881351.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['FRIED_POTATOES'] = brfss_reduced['FRIED_POTATOES'].replace({777: '', 999: ''})

In [15]:
brfss_reduced['FRIED_POTATOES'].value_counts()

1.0    180869
2.0    155732
3.0     57327
         6654
Name: FRIED_POTATOES, dtype: int64

In [16]:
brfss_reduced['E_CIGARETTES'] = np.where((brfss_reduced['E_CIGARETTES'] == 3) & (brfss_reduced['E_CIGARETTES'] == 4), 3, brfss_reduced['E_CIGARETTES'])

C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\225446308.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['E_CIGARETTES'] = np.where((brfss_reduced['E_CIGARETTES'] == 3) & (brfss_reduced['E_CIGARETTES'] == 4), 3, brfss_reduced['E_CIGARETTES'])

In [17]:
brfss_reduced['HEALTH'] = brfss_reduced['HEALTH'].replace({7: '', 9: ''})
brfss_reduced['MENTAL_HEALTH'] = brfss_reduced['MENTAL_HEALTH'].replace({7: '', 9: ''})
brfss_reduced['PHYSICAL_HEALTH'] = brfss_reduced['PHYSICAL_HEALTH'].replace({7: '', 9: ''})
brfss_reduced['PHYSICAL_ACTIVITIES'] = brfss_reduced['PHYSICAL_ACTIVITIES'].replace({7: '', 9: ''})
brfss_reduced['BLOOD_PRESSURE'] = brfss_reduced['BLOOD_PRESSURE'].replace({7: '', 9: ''})
brfss_reduced['HIGH_CHOLESTEROL'] = brfss_reduced['HIGH_CHOLESTEROL'].replace({7: '', 9: ''})
brfss_reduced['SKIN_CANCER'] = brfss_reduced['SKIN_CANCER'].replace({7: '', 9: ''})
brfss_reduced['CANCER'] = brfss_reduced['CANCER'].replace({7: '', 9: ''})
brfss_reduced['BRONCHITIS'] = brfss_reduced['BRONCHITIS'].replace({7: '', 9: ''})
brfss_reduced['DEPRESSIVE_DISORDER'] = brfss_reduced['DEPRESSIVE_DISORDER'].replace({7: '', 9: ''})
brfss_reduced['KIDNEY_DISEASE'] = brfss_reduced['KIDNEY_DISEASE'].replace({7: '', 9: ''})
brfss_reduced['DIABETES'] = brfss_reduced['DIABETES'].replace({7: '', 9: ''})
brfss_reduced['DIFFICULTY_WALKING'] = brfss_reduced['DIFFICULTY_WALKING'].replace({7: '', 9: ''})
brfss_reduced['SMOKE'] = brfss_reduced['SMOKE'].replace({7: '', 9: ''})
brfss_reduced['TABACCO_PRODUCTS'] = brfss_reduced['TABACCO_PRODUCTS'].replace({7: '', 9: ''})
brfss_reduced['E_CIGARETTES'] = brfss_reduced['E_CIGARETTES'].replace({7: '', 9: ''})
brfss_reduced['HEAVY_DRINKERS'] = brfss_reduced['HEAVY_DRINKERS'].replace({7: '', 9: ''})
brfss_reduced['HIV'] = brfss_reduced['HIV'].replace({7: '', 9: ''})
brfss_reduced['FRUITS'] = brfss_reduced['FRUITS'].replace({7: '', 9: ''})
brfss_reduced['VEGETABLES'] = brfss_reduced['VEGETABLES'].replace({7: '', 9: ''})

C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['HEALTH'] = brfss_reduced['HEALTH'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['MENTAL_HEALTH'] = brfss_reduced['MENTAL_HEALTH'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['PHYSICAL_HEALTH'] = brfss_reduced['PHYSICAL_HEALTH'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['PHYSICAL_ACTIVITIES'] = brfss_reduced['PHYSICAL_ACTIVITIES'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['BLOOD_PRESSURE'] = brfss_reduced['BLOOD_PRESSURE'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['HIGH_CHOLESTEROL'] = brfss_reduced['HIGH_CHOLESTEROL'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['SKIN_CANCER'] = brfss_reduced['SKIN_CANCER'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['CANCER'] = brfss_reduced['CANCER'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['BRONCHITIS'] = brfss_reduced['BRONCHITIS'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['DEPRESSIVE_DISORDER'] = brfss_reduced['DEPRESSIVE_DISORDER'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['KIDNEY_DISEASE'] = brfss_reduced['KIDNEY_DISEASE'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['DIABETES'] = brfss_reduced['DIABETES'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['DIFFICULTY_WALKING'] = brfss_reduced['DIFFICULTY_WALKING'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['SMOKE'] = brfss_reduced['SMOKE'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['TABACCO_PRODUCTS'] = brfss_reduced['TABACCO_PRODUCTS'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['E_CIGARETTES'] = brfss_reduced['E_CIGARETTES'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['HEAVY_DRINKERS'] = brfss_reduced['HEAVY_DRINKERS'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['HIV'] = brfss_reduced['HIV'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['FRUITS'] = brfss_reduced['FRUITS'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_15900\4012235340.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['VEGETABLES'] = brfss_reduced['VEGETABLES'].replace({7: '', 9: ''})

In [18]:
brfss_reduced.to_csv('brfss_reduced.csv', index=False)